export const cars = [
  {
    _id: '64d4e6e6f3b6c200fdf05d1a',
    name: 'Tesla Model 3',
    description:
      'An affordable electric sedan with impressive range and performance.',
    images: [
      'https://example.com/tesla-model3-1.jpg',
      'https://example.com/tesla-model3-2.jpg',
    ],
    color: 'Midnight Silver',
    isElectric: true,
    seats: 5,
    brand: 'Tesla',
    status: 'available',
    features: ['Autopilot', 'Long Range', 'Fast Charging'],
    pricePerHour: 60,
    isDeleted: false,
    createdAt: '2024-08-01T10:00:00Z',
    updatedAt: '2024-08-10T12:30:00Z',
    __v: 0,
  },
  {
    _id: '64d4e6e6f3b6c200fdf05d2b',
    name: 'Ford Mustang GT',
    description:
      'A powerful sports car with a classic design and modern features.',
    images: [
      'https://example.com/ford-mustang-gt-1.jpg',
      'https://example.com/ford-mustang-gt-2.jpg',
    ],
    color: 'Race Red',
    isElectric: false,
    seats: 4,
    brand: 'Ford',
    status: 'available',
    features: ['V8 Engine', 'Leather Seats', 'Apple CarPlay'],
    pricePerHour: 75,
    isDeleted: false,
    createdAt: '2024-08-02T11:00:00Z',
    updatedAt: '2024-08-12T13:45:00Z',
    __v: 1,
  },
  {
    _id: '64d4e6e6f3b6c200fdf05d3c',
    name: 'BMW X5',
    description:
      'A luxury SUV offering spacious interior and advanced technology.',
    images: [
      'https://example.com/bmw-x5-1.jpg',
      'https://example.com/bmw-x5-2.jpg',
    ],
    color: 'Alpine White',
    isElectric: false,
    seats: 5,
    brand: 'BMW',
    status: 'unavailable',
    features: [
      'Navigation System',
      'Panoramic Sunroof',
      'Adaptive Cruise Control',
    ],
    pricePerHour: 85,
    isDeleted: false,
    createdAt: '2024-08-03T12:00:00Z',
    updatedAt: '2024-08-13T14:00:00Z',
    __v: 0,
  },
  {
    _id: '64d4e6e6f3b6c200fdf05d4d',
    name: 'Audi A4',
    description:
      'A stylish and comfortable sedan with a refined driving experience.',
    images: [
      'https://example.com/audi-a4-1.jpg',
      'https://example.com/audi-a4-2.jpg',
    ],
    color: 'Mythos Black',
    isElectric: false,
    seats: 5,
    brand: 'Audi',
    status: 'available',
    features: ['Leather Upholstery', 'Bluetooth', 'Rearview Camera'],
    pricePerHour: 70,
    isDeleted: false,
    createdAt: '2024-08-04T13:00:00Z',
    updatedAt: '2024-08-14T15:15:00Z',
    __v: 1,
  },
  {
    _id: '64d4e6e6f3b6c200fdf05d5e',
    name: 'Chevrolet Traverse',
    description:
      'A spacious SUV ideal for families with plenty of room and comfort.',
    images: [
      'https://example.com/chevrolet-traverse-1.jpg',
      'https://example.com/chevrolet-traverse-2.jpg',
    ],
    color: 'Summit White',
    isElectric: false,
    seats: 7,
    brand: 'Chevrolet',
    status: 'available',
    features: [
      'Third-Row Seating',
      'Navigation System',
      'Blind Spot Monitoring',
    ],
    pricePerHour: 65,
    isDeleted: false,
    createdAt: '2024-08-05T14:00:00Z',
    updatedAt: '2024-08-15T16:30:00Z',
    __v: 0,
  },
  {
    _id: '64d4e6e6f3b6c200fdf05d6f',
    name: 'Hyundai Kona Electric',
    description:
      'A compact electric SUV with modern features and a practical design.',
    images: [
      'https://example.com/hyundai-kona-electric-1.jpg',
      'https://example.com/hyundai-kona-electric-2.jpg',
    ],
    color: 'Pulse Red',
    isElectric: true,
    seats: 5,
    brand: 'Hyundai',
    status: 'available',
    features: ['Fast Charging', 'Apple CarPlay', 'Automatic Emergency Braking'],
    pricePerHour: 55,
    isDeleted: false,
    createdAt: '2024-08-06T15:00:00Z',
    updatedAt: '2024-08-16T17:45:00Z',
    __v: 1,
  },
  {
    _id: '64d4e6e6f3b6c200fdf05d7g',
    name: 'Nissan Altima',
    description:
      'A midsize sedan known for its smooth ride and efficient performance.',
    images: [
      'https://example.com/nissan-altima-1.jpg',
      'https://example.com/nissan-altima-2.jpg',
    ],
    color: 'Gun Metallic',
    isElectric: false,
    seats: 5,
    brand: 'Nissan',
    status: 'available',
    features: ['Bluetooth', 'Navigation System', 'Forward Collision Warning'],
    pricePerHour: 40,
    isDeleted: false,
    createdAt: '2024-08-07T16:00:00Z',
    updatedAt: '2024-08-17T18:00:00Z',
    __v: 0,
  },
  {
    _id: '64d4e6e6f3b6c200fdf05d8h',
    name: 'Jaguar I-PACE',
    description:
      'A high-performance electric SUV with luxury and advanced technology.',
    images: [
      'https://example.com/jaguar-ipace-1.jpg',
      'https://example.com/jaguar-ipace-2.jpg',
    ],
    color: 'Corris Gray',
    isElectric: true,
    seats: 5,
    brand: 'Jaguar',
    status: 'available',
    features: ['All-Wheel Drive', 'Leather Seats', 'Surround Camera System'],
    pricePerHour: 95,
    isDeleted: false,
    createdAt: '2024-08-08T17:00:00Z',
    updatedAt: '2024-08-18T19:15:00Z',
    __v: 1,
  },
  {
    _id: '64d4e6e6f3b6c200fdf05d9i',
    name: 'Kia Soul',
    description:
      'A quirky compact car with a distinctive design and practical features.',
    images: [
      'https://example.com/kia-soul-1.jpg',
      'https://example.com/kia-soul-2.jpg',
    ],
    color: 'Neon Orange',
    isElectric: false,
    seats: 5,
    brand: 'Kia',
    status: 'available',
    features: ['Bluetooth', 'Backup Camera', 'Apple CarPlay'],
    pricePerHour: 35,
    isDeleted: false,
    createdAt: '2024-08-09T18:00:00Z',
    updatedAt: '2024-08-19T20:30:00Z',
    __v: 0,
  },
];

export const reviews = [
  {
    id: 1,
    name: 'Alice Johnson',
    rating: 5,
    comment:
      'Excellent service! The car was clean and well-maintained. Highly recommend.',
    date: '2024-08-20',
  },
  {
    id: 2,
    name: 'Bob Smith',
    rating: 4,
    comment:
      'Good experience overall, but the pick-up process could be improved.',
    date: '2024-08-18',
  },
  {
    id: 3,
    name: 'Charlie Brown',
    rating: 3,
    comment:
      'Average service. The car was fine, but the customer support was lacking.',
    date: '2024-08-15',
  },
  {
    id: 4,
    name: 'Diana Ross',
    rating: 5,
    comment:
      'Fantastic rental! Smooth transaction and a great car. Will use again.',
    date: '2024-08-14',
  },
  {
    id: 5,
    name: 'Edward White',
    rating: 2,
    comment:
      'Not satisfied. The car had several issues and the return process was slow.',
    date: '2024-08-12',
  },
  {
    id: 6,
    name: 'Fiona Green',
    rating: 4,
    comment:
      'Very good service. The car was in excellent condition and the staff was friendly.',
    date: '2024-08-10',
  },
  {
    id: 7,
    name: 'George King',
    rating: 5,
    comment:
      'Exceptional experience! Easy booking and the car was perfect for our trip.',
    date: '2024-08-08',
  },
  {
    id: 8,
    name: 'Hannah Adams',
    rating: 3,
    comment:
      'Decent car but the service was not up to the mark. Expected better.',
    date: '2024-08-05',
  },
  {
    id: 9,
    name: 'Ian Lee',
    rating: 4,
    comment:
      'Good value for money. The car was nice and the overall experience was positive.',
    date: '2024-08-03',
  },
  {
    id: 10,
    name: 'Jenna Clark',
    rating: 5,
    comment: 'Amazing service! Everything went smoothly from start to finish.',
    date: '2024-08-01',
  },
];

export const locations = [
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Jacksonville',
  'San Francisco',
  'Columbus',
  'Indianapolis',
  'Charlotte',
  'San Francisco',
  'Seattle',
  'Denver',
  'Washington',
];

export const insurances = [
  'Collision Damage Waiver (CDW)',
  'Loss Damage Waiver (LDW)',
  'Supplemental Liability Insurance (SLI)',
  'Personal Accident Insurance (PAI)',
  'Personal Effects Coverage (PEC)',
  'Roadside Assistance',
];

export const carBrands = [
  'Acura',
  'Alfa Romeo',
  'Audi',
  'BMW',
  'Buick',
  'Cadillac',
  'Chevrolet',
  'Chrysler',
  'Citroën',
  'Dodge',
  'Fiat',
  'Ford',
  'Genesis',
  'GMC',
  'Honda',
  'Hyundai',
  'Infiniti',
  'Jaguar',
  'Jeep',
  'Kia',
  'Land Rover',
  'Lexus',
  'Lincoln',
  'Maserati',
  'Mazda',
  'McLaren',
  'Mercedes-Benz',
  'Mini',
  'Mitsubishi',
  'Nissan',
  'Pagani',
  'Peugeot',
  'Porsche',
  'Ram',
  'Renault',
  'Rolls-Royce',
  'Saab',
  'Subaru',
  'Suzuki',
  'Tesla',
  'Toyota',
  'Volkswagen',
  'Volvo',
];

export const carFeatures = [
  'Air Conditioning',
  'Bluetooth Connectivity',
  'Backup Camera',
  'Navigation System',
  'Cruise Control',
  'Lane Departure Warning',
  'Adaptive Cruise Control',
  'Blind Spot Monitoring',
  'Rear Cross Traffic Alert',
  'Automatic Emergency Braking',
  'Parking Sensors',
  'Leather Seats',
  'Heated Seats',
  'Ventilated Seats',
  'Power Adjustable Seats',
  'Sunroof/Moonroof',
  'Keyless Entry',
  'Push-Button Start',
  'Apple CarPlay',
  'Android Auto',
  'Touchscreen Infotainment System',
  'Premium Audio System',
  'Satellite Radio',
  'USB Ports',
  'Wi-Fi Hotspot',
  'Automatic Headlights',
];

export const carTypes = [
  'Sedan',
  'SUV',
  'Hatchback',
  'Coupe',
  'Convertible',
  'Wagon',
  'Pickup Truck',
  'Van',
  'Minivan',
  'Sportscar',
  'Crossover',
  'Luxury Car',
  'Electric Vehicle (EV)',
  'Hybrid Vehicle',
  'Off-Road Vehicle',
  'Roadster',
];


export const additionalOptions = [
  "GPS Navigation System",
  "Child Seat",
  "Additional Driver",
  "Roadside Assistance",
  "Insurance Upgrades",
  "Fuel Options",
  "Unlimited Mileage",
  "Ski Rack or Roof Box",
  "Mobile Hotspot",
  "Special Requests",
  "Airport Pick-Up/Drop-Off",
  "Extended Hours",
  "Luxury Upgrades",
  "Prepaid Tolls",
  "Pet-Friendly Options"
]
